export const LOAD_QUIZ = "LOAD_QUIZ";
export const LOAD_QUIZ_SUCCEEDED = "LOAD_QUIZ_SUCCEEDED";
export const LOAD_QUIZ_FAILED = "LOAD_QUIZ_FAILED";
export const LOAD_QUIZZES = "LOAD_QUIZZES";
export const LOAD_QUIZZES_SUCCEEDED = "LOAD_QUIZZES_SUCCEEDED";
export const LOAD_QUIZZES_FAILED = "LOAD_QUIZZES_FAILED";
export const SHOW_LIST = "SHOW_LIST";
export const SHOW_TOP = "SHOW_TOP";
